// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXwxoGoA6wIUQm46yxEasXiU5RK89-UvQ',
    appId: '1:204111305690:web:2897bd3570d09bd2e93ee3',
    messagingSenderId: '204111305690',
    projectId: 'locate-family-67e3d',
    authDomain: 'locate-family-67e3d.firebaseapp.com',
    storageBucket: 'locate-family-67e3d.appspot.com',
    measurementId: 'G-ZGST7DJLG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIgXI1KhghAeLKEah3k6gHiFcFkR7EgeU',
    appId: '1:204111305690:android:ac3604089aa6832be93ee3',
    messagingSenderId: '204111305690',
    projectId: 'locate-family-67e3d',
    storageBucket: 'locate-family-67e3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqL9I3NPKeBv-1wCgA2ae-VwRPFB9PqdM',
    appId: '1:204111305690:ios:ec53b822100706d4e93ee3',
    messagingSenderId: '204111305690',
    projectId: 'locate-family-67e3d',
    storageBucket: 'locate-family-67e3d.appspot.com',
    iosClientId: '204111305690-vffqb1hckugk1d2kbo5q0qvtdnkndiro.apps.googleusercontent.com',
    iosBundleId: 'com.example.locateWeb',
  );
}
